export const GENRE_ACTION = '/genres/action.png'
export const GENRE_ADVENTURE = '/genres/adventure.png'
export const GENRE_COMEDY = '/genres/comedy.png'
export const GENRE_DRAMA = '/genres/drama.png'
export const GENRE_FANTASY = '/genres/fantasy.png'
export const GENRE_HISTORICAL = '/genres/historical.png'
export const GENRE_HORROR = '/genres/horror.png'
export const GENRE_MYSTERY = '/genres/mystery.png'
export const GENRE_MYTHOLOGY = '/genres/mythology.png'
export const GENRE_SCIFI = '/genres/sci-fi.png'
export const GENRE_THRILLER = '/genres/thriller.png'
export const GENRE_ROMANTIC = '/genres/romantic.png'

export const AGE_CATEGORY_CHILDREN = '/age_categories/child.png'
export const AGE_CATEGORY_TEEN = '/age_categories/teen.png'
export const AGE_CATEGORY_ADULT = '/age_categories/adult.png'

export const IMAGE_STYLE_3D = '/image_style/3D.png'
export const IMAGE_STYLE_PAPER_CUT = '/image_style/paperCut.png'
export const IMAGE_STYLE_PIXEL = '/image_style/pixel.png'
export const IMAGE_STYLE_WATER_COLOR = '/image_style/watercolor.png'
export const IMAGE_STYLE_DIGITAL_ART = '/image_style/digital-art.png'

// export const LOGIN_BACKGROUND = '/login.png'
export const LOGIN_1 = '/login/login1.webp'
export const LOGIN_2 = '/login/login2.webp'
export const LOGIN_3 = '/login/login3.webp'
export const CONTACT_IMAGE = '/contact.png'
export const LOGO_FULL = '/logo_full.png'
export const LOGO = '/logo.png'
export const LOGO_MINI = '/logo_mini.png'
