export const GENRE_ACTION = '/genres/action.png'
export const GENRE_ADVENTURE = '/genres/adventure.png'
export const GENRE_COMEDY = '/genres/comedy.png'
export const GENRE_DRAMA = '/genres/drama.png'
export const GENRE_FANTASY = '/genres/fantasy.png'
export const GENRE_HISTORICAL = '/genres/historical.png'
export const GENRE_HORROR = '/genres/horror.png'
export const GENRE_MYSTERY = '/genres/mystery.png'
export const GENRE_MYTHOLOGY = '/genres/mythology.png'
export const GENRE_SCIFI = '/genres/sci-fi.png'
export const GENRE_THRILLER = '/genres/thriller.png'
export const GENRE_ROMANTIC = '/genres/romantic.png'

export const AGE_CATEGORY_CHILDREN = '/age_categories/child.png'
export const AGE_CATEGORY_TEEN = '/age_categories/teen.png'
export const AGE_CATEGORY_ADULT = '/age_categories/adult.png'

export const IMAGE_STYLE_3D = '/image_style/3D.png'
export const IMAGE_STYLE_PAPER_CUT = '/image_style/paperCut.png'
export const IMAGE_STYLE_PIXEL = '/image_style/pixel.png'
export const IMAGE_STYLE_WATER_COLOR = '/image_style/watercolor.png'